base_url = "https://dajhub.co.uk"

title = "dajhub"

description = "Welcome to my blog where, as a Linux enthusiast, I share my tips with you. I hope you find something that is useful. "

default_language = "en"
build_search_index = true

theme = "tabi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


taxonomies = [
    {name = "tags", feed = true},
]


[markdown]
highlight_code = true
highlight_theme = "css"

[extra]

override_serif_with_sans = false

theme_switcher = true

# "light", "dark", or "" (follows user's OS theme).
default_theme = ""

# Skin available: blue, lavender, mint, red, sakura, teal, monochrome, indigo_ingot, evangelion
skin = "solarized"

# List additional stylesheets to load site-wide.
# These stylesheets should be located in your site's `static` directory.
# Example: stylesheets = ["extra1.css", "path/extra2.css"]
# You can load a stylesheet for a single post by adding it to the [extra] section of the post's front matter, following this same format.
stylesheets = []

remote_repository_url = "https://github.com/dajhub/dajhub.github.io"
remote_repository_git_platform = "github"  # Defaults to "auto".
remote_repository_branch = "main"  
show_remote_changes = true  
show_remote_source = true  

# Add a "copy" button to codeblocks.
copy_button = true

# Make code block names clickable if they are URLs (loads ~400 bytes of JavaScript).
code_block_name_links = false

force_codeblock_ltr = true

show_author = false

show_reading_time = true

show_date = true

post_listing_date = "date" # Could also be "updated" or "both"

post_listing_index_reversed = false  # Defaults to false.

footnote_backlinks = false

katex = false

mermaid = false

serve_local_mermaid = true

show_previous_next_article_links = false

invert_previous_next_article_links = false

previous_next_article_links_full_width = true

quick_navigation_buttons = false

# Add a Table of Contents to all posts, right below the title and metadata.
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
# toc = false


short_date_format = ""

separator = "•" # Used in title tag and posts metadata (between date, time to read, and tags)

compact_tags = false

tag_sorting = "name" # Could also be "frequency"

enable_cards_tag_filtering = true

invert_title_order = false

# Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = "/favicon.ico" # Placed in "static"

# Add an emoji here to use it as favicon.
# Compatibility: https://caniuse.com/link-icon-svg
# favicon_emoji = "🌱"

# Path to the fallback image for social media cards (the preview image shown when sharing a link on WhatsApp, LinkedIn…).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://welpo.github.io/tabi/blog/mastering-tabi-settings/#settings-hierarchy
# Learn how to create these images in batch and automatically:
# https://osc.garden/blog/automating-social-media-cards-zola/
# social_media_card = "img/social_cards/index.jpg"

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
#    { name = "projects", url = "projects", trailing_slash = true },
]

feed_icon = true

full_content_in_feed = false

encode_plaintext_email = true  # Setting is ignored if email is already encoded.
email = "ZGFqaHViNjNAZ21haWwuY29t" # Convert at https://www.base64encode.org/

socials = [
    { name = "github", url = "https://github.com/dajhub/", icon = "github" },
    { name = "gitlab", url = "https://gitlab.com/dajhub/", icon = "gitlab" },
    # Keep a template one
    # { name = "", url = "", icon = ""},
]


# Extra menu to show on the footer, below socials section.
footer_menu = [
#     {url = "about", name = "about", trailing_slash = true},
#     {url = "privacy", name = "privacy", trailing_slash = true},
      {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
#     {url = "https://example.com", name = "external link", trailing_slash = true},
]


allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "media-src", domains = ["'self'"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]

enable_csp = true

# If true, tabi will load the `static/custom_subset.css` file.
# If false, tabi will use the default language-specific subset (English or Spanish).
custom_subset = true



[extra.analytics]
# Specify which analytics service you want to use.
# Supported options: ["goatcounter", "umami", "plausible"]
# service = "umami"

# Unique identifier for tracking.
# For GoatCounter, this is the code you choose during signup.
# For Umami, this is the website ID.
# For Plausible, this is the domain name (e.g. "example.com").
# Note: Leave this field empty if you're self-hosting GoatCounter.
# id = "yourID"

# Optional: Specify the URL for self-hosted analytics instances.
# For GoatCounter: Base URL like "https://stats.example.com"
# For Umami: Base URL like "https://umami.example.com"
# For Plausible: Base URL like "https://plausible.example.com"
# Leave this field empty if you're using the service's default hosting.
# self_hosted_url = ""

# giscus support for comments. https://giscus.app
# Setup instructions: https://welpo.github.io/tabi/blog/comments/#setup
[extra.giscus]
# enabled_for_all_posts = false  # Enables giscus on all posts. It can be enabled on individual posts by setting `giscus = true` in the [extra] section of a post's front matter.
# automatic_loading = true  # If set to false, a "Load comments" button will be shown.
# repo = "welpo/tabi-comments"
# repo_id = "R_kgDOJ59Urw"  # Find this value in https://giscus.app/
# category = "Announcements"
# category_id = "DIC_kwDOJ59Ur84CX0QG"  # Find this value in https://giscus.app/
# mapping = "slug"  # Available: pathname; url; title; slug. "slug" will use the post's filename (slug); this is the only way to share comments between languages.
# strict_title_matching = 1  # 1 to enable, 0 to disable. https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-strict
# enable_reactions = 1  # 1 to enable, 0 to disable.
# comment_box_above_comments = false
# light_theme = "noborder_light"
# dark_theme = "noborder_dark"
# lang = ""  # Leave blank to match the page's language.
# lazy_loading = true

# utterances support for comments. https://utteranc.es
# Setup instructions: https://welpo.github.io/tabi/blog/comments/#setup
[extra.utterances]
# enabled_for_all_posts = false  # Enables utterances on all posts. It can be enabled on individual posts by setting `utterances = true` in the [extra] section of a post's front matter.
# automatic_loading = true  # If set to false, a "Load comments" button will be shown.
# repo = "yourGithubUsername/yourRepo"  # https://utteranc.es/#heading-repository
# issue_term = "slug"  # Available: pathname; url; title; slug. "slug" will use the post's filename (slug); this is the only way to share comments between languages. https://utteranc.es/#heading-mapping
# label = "💬"  # https://utteranc.es/#heading-issue-label
# light_theme = "github-light"  # https://utteranc.es/#heading-theme
# dark_theme = "photon-dark"  # https://utteranc.es/#heading-theme
# lazy_loading = true

# Hyvor Talk support for comments. https://talk.hyvor.com
[extra.hyvortalk]
# enabled_for_all_posts = false  # Enables hyvortalk on all posts. It can be enabled on individual posts by setting `hyvortalk = true` in the [extra] section of a post's front matter.
# automatic_loading = true  # If set to false, a "Load comments" button will be shown.
# website_id = "1234"
# page_id_is_slug = true  # If true, it will use the post's filename (slug) as id; this is the only way to share comments between languages. If false, it will use the entire url as id.
# lang = ""  # Leave blank to match the page's language.
# page_author = ""  # Email (or base64 encoded email) of the author.
# lazy_loading = true

# Isso support for comments. https://isso-comments.de/
# You need to self-host the backend first: https://blog.phusion.nl/2018/08/16/isso-simple-self-hosted-commenting-system/
# More info on some settings: https://isso-comments.de/docs/reference/client-config/
[extra.isso]
# enabled_for_all_posts = false  # Enables Isso on all posts. It can be enabled on individual posts by setting `isso = true` in the [extra] section of a post's front matter.
# automatic_loading = true  # If set to false, a "Load comments" button will be shown.
# endpoint_url = ""  # Accepts relative paths like "/comments/" or "/isso/", as well as full urls like "https://example.com/comments/". Include the trailing slash.
# page_id_is_slug = true  # If true, it will use the relative path for the default language as id; this is the only way to share comments between languages. If false, it will use the entire url as id.
# lang = ""  # Leave blank to match the page's language.
# max_comments_top = "inf"  # Number of top level comments to show by default. If some comments are not shown, an “X Hidden” link is shown.
# max_comments_nested = "5"  # Number of nested comments to show by default. If some comments are not shown, an “X Hidden” link is shown.
# avatar = true
# voting = true
# page_author_hashes = ""  # hash (or list of hashes) of the author.
# lazy_loading = true  # Loads when the comments are in the viewport (using the Intersection Observer API).

# h-card configuration
# Will identify you on the indieweb (see https://microformats.org/wiki/h-card)
[extra.hcard]
# Enable home page h-card.
enable = true
# Add your email to the card if extra.email is set and not encoded.
# with_mail = true
# Add your social links ('socials' config) to the card.
with_social_links = true
# Homepage url. Defaults to the value of 'base_url'.
# homepage = "https://myhomepage.net"
# avatar = "img/profile.webp"
# Display name, default to the value of 'author'.
# full_name = "John Doe"
# Small bio, as shown on social media profiles.
# biography = "Fond of the indieweb"
#
# You can add any property from https://microformats.org/wiki/h-card#Properties
# Make sure to replace all '-' characters by '_'
# Examples:
# p_nickname = "nickname"
# p_locality = "Bordeaux"
# p_country_name = "France"
